### ISSUE TITLE
'aud' claim check

### ISSUE THREAD

**Issue by naseer11** [ghdna/cognito-express#11]
As per [AWS Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html):

"The audience (aud) claim should match the app client ID created in the Amazon Cognito user pool."

The module doesn't seem to verify the 'aud' claim. Am I missing something or is this a bug?

**Comment by jclwong** [comment]
client_id (access token) === aud (id token) === Client Id (Cognito User Pool)
This library validates the **access token** (client_id) against **Cognito user pool**, and not the **id token** (aud).

**Comment by buccfer** [comment]
@naseer11 Since issues like this one have been open for so long I created a different library [aws-cognito-express](https://www.npmjs.com/package/aws-cognito-express).
