### ISSUE TITLE
Handeling refresh tokens

### ISSUE THREAD

**Issue by timkuilman** [ghdna/cognito-express#12]
First af all: great job for all of the work you have been doing on this plugin. It works like a charm! 

I was wondering if anyone has yet implemented a flow for handling expired access / id tokens and using the refresh token to retrieve a new jwt? I am thinking about building this functionality and I wonder what would be the best approach. I currently have a separate unauthenticated endpoint to which a refresh token can be send (along with the username since I think its necessary for the exchange). The cognito-express module could also catch the expired like this:

`cognitoExpress.validate(authToken, function (err, response) {
    if(err.name === 'TokenExpiredError') {} 
    if (err) {
      return res.status(401).send(err);
    }
` 
Who implemented this part and can give me some leads on how to implement this part securely?

**Comment by ghdna** [comment]
Good idea! If you figure out a way to do this, I can add it on the documentation as an option.

**Comment by timkuilman** [comment]
So my current approach is letting the client (in my case a React Native application) keep track of when it's necessary to get a new id/access. I do this by not only storing the refresh token in AsyncStorage but also the date and time when that token will expire. When the app starts (from the background or a 'cold' start) I compare that expiration date with the current date and hit an endpoint that creates a new id/access token. I think it's best to get a new token when 50 percent of the time before expiration has passed. 

This is what my refresh endpoint looks like.  

```import { CognitoUser,CognitoRefreshToken, CognitoUserPool} from 'amazon-cognito-identity-js';

export const processRefreshToken = function (req, res) {
  const {refreshToken, username} = req.body;
  const userPool = new CognitoUserPool({UserPoolId: process.env.USER_POOL_ID, ClientId: process.env.USER_CLIENT_ID});
  const userData = {Username: username, Pool: userPool};
  const cognitoUser = new CognitoUser(userData);
  const token = new CognitoRefreshToken({RefreshToken: refreshToken});

  cognitoUser.refreshSession(token,
    function (err, result) {
      if (err) {
        return res.status(401).send(err);
      }

      res.json({
        idToken: result.getIdToken().getJwtToken(),
        accessToken: result.getAccessToken().getJwtToken(),
        refreshToken: result.getRefreshToken().getToken(),
      })
    });
};
```

Two reason why I did not continue with the `if(err.name === 'TokenExpiredError` approach:
1. You'd have to send the refresh token with each api call. Refresh tokens are valid forever and I think it's a security risk to always send the token.
2. You'd have to send the username with each request as well since `new CognitoUserPool` requires a username.

**Comment by ghdna** [comment]
Good points. I think for customized controlled implementation, it might be okay. But as a module, we shouldn't be exposing refresh token to client for security reasons.
