### ISSUE TITLE
cors issue

### ISSUE THREAD

**Issue by ebuychance** [ghdna/cognito-express#14]
**Issued error msg on the client:**
`Access to XMLHttpRequest at 'http://localhost:3000/test' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

**Headers set on the server:**
`app.use("/api", authenticatedRoute);
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
  next();
});`

Any help setting the correct headers would be much appreciated!

**Comment by ghdna** [comment]
are you still having this issue?
