### ISSUE TITLE
Bogus JsonWebTokenError on maxAge value

### ISSUE THREAD

**Issue by PosicubeBeege** [ghdna/cognito-express#16]
After getting an AWS ID Token and passing it to my API using the cognito-express middleware, I get the following error:
```json
{
    "name":"JsonWebTokenError",
    "message":"\"maxAge\" should be a number of seconds or string representing a timespan eg: \"1d\", \"20h\", 60"
}
```

This is unusable.

**Comment by ghdna** [comment]
Did it ever work? If not, could you provide more info/steps to replicate this issue?
