### ISSUE TITLE
`CognitoExpress.validate()`'s `callback` parameter is optional, but is blindly invoked for error conditions

### ISSUE THREAD

**Issue by robertbullen** [ghdna/cognito-express#18]
This means that the promisified code path in `CognitoExpress.validate()` is fundamentally broken for failure scenarios.

Here are the offending lines:

https://github.com/ghdna/cognito-express/blob/86c738624b52a4de2e9e4df7bf10289564c3ae01/lib/strategy.js#L52-L63

Meanwhile, just a little further down `callback` is properly checked in two locations:

https://github.com/ghdna/cognito-express/blob/86c738624b52a4de2e9e4df7bf10289564c3ae01/lib/strategy.js#L72-L89

**Comment by robertbullen** [comment]
The unit tests mask this bug because of how they are passing an async callback:

https://github.com/ghdna/cognito-express/blob/86c738624b52a4de2e9e4df7bf10289564c3ae01/test/strategy.js#L121-L130

Because the callback is async, it will be executed after the `strategy.init()` promise, and hence the test itself, resolves. This means that the `expect` assertions occur outside of the detection of chai.

Restructuring the test as follows:

```javascript
	it("should check if Validate function can fail successfully when invalid token is passed (Promise)", async () => {
		await strategy.init(result => expect(result).to.eql(true));
		try {
			await strategy.validate("token");
		} catch (err) {
			expect(err).to.eql("Not a valid JWT token");
		};
	});
```

Surfaces the failure:

```text
  Strategy Positive Scenarios
    ✓ should check if GeneratePem function exists
    ✓ should check if jwtVerify function exists
    ✓ should check if configurationIsCorrect function exists
    ✓ should check if Validate function exists
    ✓ should check if Strategy can initialized successfully (208ms)
    ✓ should check if Validate function can fail successfully when invalid token is passed (129ms)
    1) should check if Validate function can fail successfully when invalid token is passed (Promise)
    ✓ should check if Validate function can execute successfully by detecting an expired token (134ms)


  14 passing (632ms)
  1 failing

  1) Strategy Positive Scenarios
       should check if Validate function can fail successfully when invalid token is passed (Promise):
     AssertionError: expected [TypeError: callback is not a function] to deeply equal 'Not a valid JWT token'
      at Context.it (test/strategy.js:126:19)
      at <anonymous>
```

**Comment by robertbullen** [comment]
@ghdna, do you have any thoughts on or plans for this PR?

**Comment by buccfer** [comment]
@robertbullen Since issues like this one have been open for so long I created a different library [aws-cognito-express](https://www.npmjs.com/package/aws-cognito-express).
