### ISSUE TITLE
Refactor `Strategy.init()` into an intelligent caching mechanism

### ISSUE THREAD

**Issue by robertbullen** [ghdna/cognito-express#22]
This issue stems from the comments started in #20, where it was brought up that it is unclear whether clients should be responsible for calling `init()`. The `Strategy` constructor calls `init()` and the results are cached from that point forward. Given the following fact, from this [AWS Forum post](https://forums.aws.amazon.com/message.jspa?messageID=747599#752341) (dated Nov 2016), that is currently sufficient.

> Cognito UserPool currently does not rotate keys but this behavior can be changed in future. For example, we may periodically rotate keys or allow a developer to replace the keys. We recommend that you cache each key in jwks uri against kid. Now when you process Id or Access token in your APIs, you should check the kid in JWT header and retrieve the key from cache. When your API sees token with different kid, you should query jwks uri again to check if keys have been changed and update your cache accordingly with new keys.

So to be completely safe and future-proof with the way this project is structured today, clients should explicitly call `init()` periodically. Or before every call to `validate()`, which is how most of the unit tests are written. Their execution times infer the network request for fetching the JWKs incurs a penalty on the order of 100+ milliseconds, even though that penalty is likely completely unnecessary.

`init()` could be rewritten, or perhaps effectively, merged into `validate()`, and take the advice from the forum post above with JWK caching and fetching on demand only when warranted.

This sounds like a breaking change, but could be implemented in such a way that `init()` could be left as a deprecated stub that simply resolves immediately.

**Comment by buccfer** [comment]
@robertbullen Since issues like this one have been open for so long I created a different library [aws-cognito-express.](https://www.npmjs.com/package/aws-cognito-express) .. 100% test coverage
