### ISSUE TITLE
This callback would never be called in case of error

### ISSUE THREAD

**Issue by deanshelton913** [ghdna/cognito-express#24]
https://github.com/ghdna/cognito-express/blob/86c738624b52a4de2e9e4df7bf10289564c3ae01/lib/strategy.js#L40-L44

**Comment by robertbullen** [comment]
This is a dupe of issue #19 that is fixed in PR #20, which was just merged into master this morning.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
