### ISSUE TITLE
tokenExpiration question

### ISSUE THREAD

**Issue by burkeallen** [ghdna/cognito-express#27]
Since the accessToken contains the token expiration timestamp in it,  what is the purpose of defining the token expiration on the config?

Does CognitoExpress return an invalid response if the Token is in fact expired?  and is based on on the auth_time + tokenExpiration values or the accessToken "exp" value?

thank you in advance for your response.

**Comment by ghdna** [comment]
Yes, once the token expires, you get this error:
```javascript
{
    "name": "TokenExpiredError",
    "message": "jwt expired",
    "expiredAt": "2017-07-05T16:41:59.000Z"
}
```

**Comment by burkeallen** [comment]
Thank you for the quick response, how is the expiration determined?

is it based on the actual "exp" value in the token? or is it based on the tokenExpiration value + the "auth_time" value in the token?

**Comment by ghdna** [comment]
Bit rusty on the exact mechanics but I could point you to the official documentation on this to avoid giving false/outdated info: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-id-token

**Comment by burkeallen** [comment]
thanks, Cognito validates based on the exp value in the access token.

just wondering why "tokenExpiration" is something that gets set in the cognitoExpress Config, I guess I can dig into the code to find out for sure.

**Comment by ghdna** [comment]
Oh that I can answer, since it relates to this package and not AWS Cognito. The default expiration time is 1 hour, as set by AWS Cognito. BUT should you want to have a shorter expiration time, say 5 minutes, you can set your own token expiration in CognitoExpress config.

**Comment by burkeallen** [comment]
Thank you

**Comment by dushyant89** [comment]
hey @ghdna thanks for building the library. I was hoping to read more on the part where we use the url `.well-known/jwks.json` to fetch some response and the data in the response lays the foundation for unpacking/decoding the jwt, this doesn't seem like standard public key cryptography, can you share some resources on the strategy used ?
