### ISSUE TITLE
Local read of JWT tokens

### ISSUE THREAD

**Issue by shnplr** [ghdna/cognito-express#3]
Hi,

Would it be possible to provide ability to load JWT tokens from file system (for example) and pass them into the lib rather than making network call?  The reason is our corporate proxy blocks the request from NodeJS express app, which is the main reason I'm thinking of switching from server side to client side authentication, which means I need to use the tokens.

In this scenario I would probably package the tokens with the application.  

p.s. Do you know if the tokens change once the user pool is created? - aws documentation isn't clear on that. For the user pools I've created there seem to be always 2 tokens.

Thanks,
Paul

**Comment by ghdna** [comment]
Not sure I follow. The JWT token is generated by Amazon Cognito and is valid for 1 hour. It also includes refresh token which can be used to renew JWT token. The PEM file that cognito-express generates is the 1st time its initialized. This stays static.

**Comment by shnplr** [comment]
Sorry I'm new to using Cognito's JWT strategy so I may be getting confused. I was under the impression this library needed to make a HTTP connection to Cognito to download well known tokens 
e.g.
Looking at the code I could see 
```
init(callback) {
return request(`${this.iss}/.well-known/jwks.json`)
```

Behind our corporate proxy this does not work and I see error such as

```
Unhandled rejection TypeError: Unable to generate certificate due to 
RequestError: Error: tunneling socket could not be established, cause=write EPROTO 140342802409280:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```

Is it not possible for this library NOT to make any network connection if I can provide the well known tokens myself in the distribution?

Or is there some way this library can act differently if https_proxy is defined?

Cheers,
Paul

**Comment by ghdna** [comment]
oh ok, I understand now. The request is being made to this URL: https://cognito-idp.${YOUR_REGION}.amazonaws.com/${YOUR_POOLID}/.well-known/jwks.json.

And yes, you should be able to simply hit this in your browser and see a JSON response. 

In the init method, this response is used to generate the pem file. You can modify this method to not make that HTTP call and instead iterate over a custom variable containing the response you got previously from your browser. Try it out and let me know if that works better.

**Comment by shnplr** [comment]
OK so your recommendation is to copy the code to a separate repo and make the necessary change to suit the requirement?
Thats fine if thats the case we can close the issue.
By the way, great code! thanks very much
