### ISSUE TITLE
How to deal with constructor background error

### ISSUE THREAD

**Issue by jobarjo** [ghdna/cognito-express#39]
Hello,

From what I understand, when the constructor is called, there is an http request launched in the background to download the `jwks.json`. If for some reason that HTTP request fails, an error is then thrown. 

Is there any way to handle that error during the constructor instantiation? I'd like to avoid continuing in the code if this fails.

Thanks,
Joel

**Comment by ghdna** [comment]
If it doesn't initialize, it won't proceed to the validate function
