### ISSUE TITLE
npm audit - json-schema is vulnerable to Prototype Pollution 

### ISSUE THREAD

**Issue by evandwight** [ghdna/cognito-express#53]
**Problem:** npm audit has identified a security with cognito-express version 2.0.19

[json-schema is vulnerable to Prototype Pollution](https://github.com/advisories/GHSA-896r-f27r-55mw) due to the request library.

**Fix:** use a different http request library as request has been deprecated.

**Comment by ghdna** [comment]
Yeah, changing this.

**Comment by jordins** [comment]
hi! first of all, thanks for this library! I would like to know if there's any update on this.

**Comment by ghdna** [comment]
Just pushed an update on GH (not NPM) replacing `request` with `axios`
Let me know if the latest master works well with your workload. If it passes all checks, I'll push to NPM.

**Comment by jordins** [comment]
thanks @ghdna! Just tested your latest changes and it works! 🎉 
Will wait for the new npm release.
Thanks again!

**Comment by ghdna** [comment]
Awesome. I have pushed the latest to NPM (v3.0.1)
Thanks again for pushing on this. Closing this now.
