### ISSUE TITLE
Would be awesome to use promises for this

### ISSUE THREAD

**Issue by kjanoudi** [ghdna/cognito-express#7]
Had to write a wrapper so that i can use this library with async/await, would be nice to have this use promises internally

```
export default token =>
  new Promise((resolve, reject) => {
    cognitoExpress.validate(token, (err, response) => {
      if (err) {
        return reject(err)
      }
      resolve(response)
    })
  })

```

**Comment by ghdna** [comment]
Good idea. Let me look into it.

**Comment by lfreneda** [comment]
Good idea [2], but anyway, nice work @ghdna, u r the guy :+1:

**Comment by ghdna** [comment]
Sorry to leave this thread hanging. Tested locally and merged. Thanks @rivertam
