### ISSUE TITLE
Add TypeScript Support to cognito-express

### ISSUE THREAD

**Issue by naishe** [ghdna/cognito-express#9]
```
src/middleware/index.ts:1:28 - error TS7016: Could not find a declaration file for module 'cognito-express'. '/Users/naishe/app/node_modules/cognito-express/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/cognito-express` if it exists or add a new declaration (.d.ts) file containing `declare module 'cognito-express';`
```

Please add support for TypeScript.

**Comment by bugeats** [comment]
It's not a TypeScript project. Why should it be? Can you give one reason why type hinting would enhance this project in any way? Making your catch-all error messages go away is not a reason.

**Comment by naishe** [comment]
Compile time type checking maybe? It is a nice to have feature. You can get away with it with `"noImplicitAny": false` in tsconfig. 

I think it is OK to close this issue if it is not in the roadmap. Thanks.

**Comment by ghdna** [comment]
Not on the road map currently. But I'd be happy to revisit if there is more interest for it.

**Comment by cryptiklemur** [comment]
Would love to see types added. Might be beneficial to re-open this ticket

**Comment by adamAtDemarq** [comment]
https://medium.com/@jtomaszewski/why-typescript-is-the-best-way-to-write-front-end-in-2019-feb855f9b164

this is why it should have typescript :)

**Comment by scgarland191** [comment]
I love this library and use it with TS, so I would dig types for it as well!

**Comment by rodrigofeijao** [comment]
Is there any plans to get TS support to this?

**Comment by iangabrielsanchez** [comment]
looking forward to this

**Comment by ioannisKatri** [comment]
looking forward to this as well

**Comment by yukari1414** [comment]
looking forward +1

**Comment by abe-mused** [comment]
looking forward to this as well

**Comment by naishe** [comment]
The PR https://github.com/ghdna/cognito-express/pull/52 is for this issue. The PR also upgrades the library dependencies and gets rid of deprecated library that's still being used. Here is the summary

1. Updated the project to Typescript
2. Adds appropriate types and gets rid of inconsistencies like throwing `Error` vs throwing a string.
3. Libraries like `request`, `request-promise`, and `istanbul` are deprecated, replaced them with `fetch` and `nyc`
4. Expanded test coverage

I haven't tested this version extensively, but I am using a version of congnito-express with very similar changes for a almost two years without hiccup.

I am open to suggestions.

**Comment by YenHub** [comment]
Why was this issue closed? The PR was closed without comment (or being merged) :o(
